name: histo3.10
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - decorator=5.1.1
  - expat=2.6.2
  - filelock=3.16.1
  - fontconfig
  - freetype
  - fsspec=2024.10.0
  - h11=0.14.0
  - httpx=0.27.0
  - icu
  - idna=3.7
  - ipykernel
  - ipython
  - jinja2
  - jupyterlab
  - matplotlib-inline
  - numpy
  - openslide=4.0.0
  - openslide-python=1.3.1
  - pandas
  - pillow
  - pip
  - pytest
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - sqlite
  - tqdm
  - zlib
  - lz4-c
  - markupsafe
  - mistune
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - requests
  - sympy
  - tornado
  - typing-extensions
  - urllib3
  - zipp
  - mkl
  - pip:
      - openslide-python
